### ISSUE TITLE
Allow custom js entry filename instead of `main`

### ISSUE THREAD

**Issue by DamChtlv** [WP-Performance/presswind-assets#1]
## Issue
Code only allow for `main.js` at top level actually:
https://github.com/WP-Performance/presswind-assets/blob/318b75d56e810c5d6387bb1138bfe836b1b09c2c/src/PWVite.php#L141C113-L141C119

## Proposal
I would like to use `src/index.js` from my theme for example, which could be set using an argument or filter :)

**Comment by ipatate** [comment]
thanks for proposal, it's done with latest version
