### ISSUE TITLE
Allow or check for http protocol used

### ISSUE THREAD

**Issue by DamChtlv** [WP-Performance/presswind-assets#2]
## Issue
Code only allow for `https`:
https://github.com/WP-Performance/presswind-assets/blob/318b75d56e810c5d6387bb1138bfe836b1b09c2c/src/PWVite.php#L141

## Proposal
My local dev env doesn't use https _(don't have certificate)_
I would like a way to specify it

**Comment by ipatate** [comment]
thanks for idea, it's done with latest version
